name       : haskell-reflection
version    : 2.1.2
release    : 1
source     :
    - https://hackage.haskell.org/package/reflection-2.1.2/reflection-2.1.2.tar.gz : a909882c04b24016bedb85587c09f23cf06bad71a2b1f7e781e89abaa6023c39
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package addresses the configuration problem which is propagating configurations that are available at run-time
description: |
    This package addresses the configuration problem which is propagating configurations that are available at run-time, allowing multiple configurations to coexist without resorting to mutable global variables or System.IO.Unsafe.unsafePerformIO.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
