name       : haskell-reflection
version    : 2.1.5
release    : 3
source     :
    - https://hackage.haskell.org/package/reflection-2.1.5/reflection-2.1.5.tar.gz : 272ee9bffb722047067296a34f68d7450e3f6abfbe62eed02a9cef20ed212977
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package addresses the configuration problem which is propagating configurations that are available at run-time
description: |
    This package addresses the configuration problem which is propagating configurations that are available at run-time, allowing multiple configurations to coexist without resorting to mutable global variables or System.IO.Unsafe.unsafePerformIO.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
