name       : haskell-reflection
version    : 2.1.3
release    : 2
source     :
    - https://hackage.haskell.org/package/reflection-2.1.3/reflection-2.1.3.tar.gz : 88f81923abd7211e51de7071cd5800b30784e374c193de8cdd7b1c201f8de405
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package addresses the configuration problem which is propagating configurations that are available at run-time
description: |
    This package addresses the configuration problem which is propagating configurations that are available at run-time, allowing multiple configurations to coexist without resorting to mutable global variables or System.IO.Unsafe.unsafePerformIO.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
